[project]
name = "agentic-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.81.4",
    "python-dotenv>=1.2.1",
]
